CREATE TABLE IF NOT EXISTS word (
     id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
     word VARCHAR(50) NOT NULL,
     schoolyear INT NOT NULL,  
     unit VARCHAR(10) NOT NULL,
     mean VARCHAR(50) NOT NULL
 );